import { Property } from '../types';

export const showcaseProperties: Property[] = [
  {
    id: 'villa-amaya',
    name: 'Villa Amaya, Ibiza',
    description: 'Clifftop sanctuary with panoramic Balearic views, private helipad, and dedicated sommelier.',
    location: 'Ibiza, Spain',
    price_per_night: 4200,
    images: ['https://images.unsplash.com/photo-1505691938895-1758d7feb511'],
    amenities: ['Infinity pool', 'Private chef', 'Wellness suite'],
    max_guests: 8,
    bedrooms: 5,
    bathrooms: 6,
    rating: 4.9,
    review_count: 47,
    status: 'active',
  },
  {
    id: 'ryokan-hikari',
    name: 'Ryokan Hikari',
    description: 'Heritage Kyoto retreat bridging minimalist design and onsen rituals curated by master artisans.',
    location: 'Kyoto, Japan',
    price_per_night: 3100,
    images: ['https://images.unsplash.com/photo-1470246973918-29a93221c455'],
    amenities: ['Onsen', 'Tea master', 'Tatami suites'],
    max_guests: 6,
    bedrooms: 4,
    bathrooms: 4,
    rating: 4.8,
    review_count: 89,
    status: 'active',
  },
  {
    id: 'desert-oracle',
    name: 'Desert Oracle Pavilion',
    description: 'Architectural desert pavilion with stargazing observatory, desert sommeliers, and camel safaris.',
    location: 'AlUla, Saudi Arabia',
    price_per_night: 5200,
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85'],
    amenities: ['Observatory', 'Butler service', 'Camel safaris'],
    max_guests: 4,
    bedrooms: 3,
    bathrooms: 3,
    rating: 5.0,
    review_count: 23,
    status: 'active',
  },
];
